tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'wez/wezterm'

brew 'ag'
brew 'bat'
brew 'curl'
brew 'deno'
brew 'direnv'
brew 'fzf'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'go'
brew 'starship'
brew 'tig'
brew 'tree'
brew 'wget'

cask 'firefox'
cask 'google-chrome'
cask 'hyper'
cask 'font-sauce-code-pro-nerd-font'
cask 'font-space-mono-nerd-font'
cask 'raycast'
cask 'visual-studio-code'
cask 'wez/wezterm/wezterm'
